### ISSUE TITLE
why can't I accept notification ?

### ISSUE THREAD

**Issue by Sanbingo** [diPhantxm/ozon-api-client#112]
create a restful api, test type_ping is success,but type_new_posting is failure. Use local api test is ok. Ozon backend would push type_new_posting when order is created? I need your help, best wishes!

**Comment by diPhantxm** [comment]
> create a restful api, test type_ping is success,but type_new_posting is failure. Use local api test is ok. Ozon backend would push type_new_posting when order is created? I need your help, best wishes!

Hi!
Could you please provide some details on what you're trying to do?
As [doc](https://docs.ozon.ru/api/seller/en/#section/New-shipment) says, `TYPE_NEW_POSTING` is pushed when a new order has been placed in FBS and rFBS schemes.

**Comment by Sanbingo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by diPhantxm** [comment]
Hi @Sanbingo 
If you don't have any questions left, please close issue or I will close it in a week due to inactivity.

**Comment by Sanbingo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
