### ISSUE TITLE
Доступность складов и бронирование времени

### ISSUE THREAD

**Issue by DerLokich** [diPhantxm/ozon-api-client#113]
Добрый день!
С помощью этой библиотеки можно отследить склады и забронировать время в них?

**Comment by diPhantxm** [comment]
Привет!
В этой библиотеке поддерживаются все ручки доступные Ozon Seller API, их можно посмотреть здесь: https://docs.ozon.ru/api/seller/
Думаю тебе стоит взглянуть на эту ручку: https://docs.ozon.ru/api/seller/#operation/SupplyDraftAPI_DraftTimeslotInfo

**Comment by diPhantxm** [comment]
@DerLokich 
Привет! Если у тебя все получилось и не осталось больше вопросов, закрой, пожалуйста, issue

**Comment by diPhantxm** [comment]
> На данный момент ещё не пробовал, но не думаю, что возникнут сложности. Спасибо за наводку!)

Привет! Я, кажется, понял что тебе нужно. У API было обновление 31 октября, я только до него дошел, обновил либу. Глянь вот на эту ручки и подобные ниже
https://github.com/diPhantxm/ozon-api-client/blob/master/ozon/fbo.go#L649
