### ISSUE TITLE
unable to change default http client and context

### ISSUE THREAD

**Issue by whoamineverminds** [diPhantxm/ozon-api-client#35]
Now method NewClient of ozon and core package uses context.Background() and http.DefaultClient

Want this methods to get last param like configs ...Configuration to configure core httpclient

type Configuration func(o *Client)

func WithHttpClient(client HttpClient) Configuration {
	return func(c *Client) {
		c.client = client
	}
}

func WithContext(ctx context.Context) Configuration {
	return func(c *Client) {
		c.ctx = ctx
	}
}

**Comment by s1berc0de** [comment]
PR: https://github.com/diPhantxm/ozon-api-client/pull/36

**Comment by diPhantxm** [comment]
Hi!
Thank you for reporting your issue. Sounds like a great idea. 
If you want, you can open pr with the implementation.
