### ISSUE TITLE
I need some help. Why does such a simple program have an error. I've been troubled for a long time

### ISSUE THREAD

**Issue by 2424719479** [diPhantxm/ozon-api-client#56]
![错误](https://github.com/diPhantxm/ozon-api-client/assets/94888456/f1a2404f-7af9-4d54-a559-952b8305f3db)

I need some help. Why does such a simple program have an error. I've been troubled for a long time

**Comment by diPhantxm** [comment]
Hi. It seems you are not using this library. Please if you use golang and you have a question about this exact library, show me the code that is not working.
If you have a question about Ozon Seller API itself, you are in a wrong place, check out this section https://docs.ozon.ru/global/en/api/intro/?country=CN
