### ISSUE TITLE
invalid readme signature

### ISSUE THREAD

**Issue by zloyleshiy** [diPhantxm/ozon-api-client#58]
привет! обновляю либу и в инит клиента добавился интересный момент, не описанный в ридми
![image](https://github.com/diPhantxm/ozon-api-client/assets/17111449/3f74e35d-9670-478b-87d6-23df54030c20)

сигнатура отличается от того что в readme

лечится так
`client := ozon.NewClient(http.DefaultClient, "my-client-id", "my-api-key")`

паправьте плз или readme или инициализацию клиента так, чтобы не надо было в него подкладывать дефолтный клиент (тк это выглядит как минимум странно)

**Comment by diPhantxm** [comment]
Привет!
Спасибо, что поделился своим вопросом. Структура клиента была пересмотрена и обновлена. Выкатил новый релиз с этими изменениями. Сейчас также обновил пример использования библиотеки в README.
Пожалуйста, обнови версию пакета в проекта и можешь пользоваться :)

**Comment by zloyleshiy** [comment]
спасибо, забрал
