### ISSUE TITLE
CreateOrUpdateProduct request receive "414 Request-URI Too Large" error

### ISSUE THREAD

**Issue by JoeyFrancisTribbiani** [diPhantxm/ozon-api-client#63]

**Comment by JoeyFrancisTribbiani** [comment]
can't upload picture...

**Comment by diPhantxm** [comment]
Hi!
Thank your for your issue. I'll check and respond

**Comment by JoeyFrancisTribbiani** [comment]
If this line is commented out, this error will not be reported.	
client.go - line 69:
    httpReq.URL.RawQuery = rawQuery

**Comment by diPhantxm** [comment]
> If this line is commented out, this error will not be reported. client.go - line 69: httpReq.URL.RawQuery = rawQuery

Seems like default value feature was implemented incorrectly. It adds default values into query parameters instead of replacing values in body of the request
I temporarily removed this feature until I fix it. You can `go get` last commit from this repo to escape this error

**Comment by JoeyFrancisTribbiani** [comment]
OK，非常感谢！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by diPhantxm** [comment]
I reimplemented this feature. Seems working. If you meet another bug, please feel free to reopen this issue
