### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by JoeyFrancisTribbiani** [diPhantxm/ozon-api-client#68]
You have a spelling mistake here：
```
type CreateOrUpdateAttributeValue struct {
// Directory identifier
DictionaryValueId int64 json:"dictrionary_value_id"

// Value from the directory
Value string `json:"value"`
}
```

it should be dictionary_value_id not dictrionary_value_id

**Comment by diPhantxm** [comment]
Hi @JoeyFrancisTribbiani. Thank you for finding a problem. I've pushed fix. If you need this fix right now, you can `go get` last commit into your project

**Comment by diPhantxm** [comment]
@JoeyFrancisTribbiani Is it solved now? Can I close this issue?

**Comment by JoeyFrancisTribbiani** [comment]
yes！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
