### ISSUE TITLE
client.Products().CreateProductByOzonID() receive 410 code

### ISSUE THREAD

**Issue by JoeyFrancisTribbiani** [diPhantxm/ozon-api-client#75]
client.Products().CreateProductByOzonID receive 410 code， 
and (*(importResp)).CommonResponse.Message = "obsolete method cannot be used"
client version v1.11.0

**Comment by diPhantxm** [comment]
Hi!
Thank you for reporting a problem.
I've checked this method in Ozon Seller API documentation, it doesn't say that it's obsolete. I also tried to send a request via Postman and I got the same error. Same thing happens if I try this method via console directly in Ozon Seller API documentation.
I am not sure it relates to this library, but I asked Ozon about this issue. Perhaps, they forgot to mark this method as obsolete. Will be back when I get a response.

**Comment by JoeyFrancisTribbiani** [comment]
> Hi! Thank you for reporting a problem. I've checked this method in Ozon Seller API documentation, it doesn't say that it's obsolete. I also tried to send a request via Postman and I got the same error. Same thing happens if I try this method via console directly in Ozon Seller API documentation. I am not sure it relates to this library, but I asked Ozon about this issue. Perhaps, they forgot to mark this method as obsolete. Will be back when I get a response.

thanks for the reply. I have a question to ask: From my rough attempts, whether it is get product Info or get product description, product-related APIs seem to be unable to obtain product information from other sellers. My approach is to first use the CreateProductByOzonID interface to import it into the seller's system, and then obtain its product information. If this interface is really deprecated, is there any way to get product information from other sellers?

**Comment by diPhantxm** [comment]
> > Hi! Thank you for reporting a problem. I've checked this method in Ozon Seller API documentation, it doesn't say that it's obsolete. I also tried to send a request via Postman and I got the same error. Same thing happens if I try this method via console directly in Ozon Seller API documentation. I am not sure it relates to this library, but I asked Ozon about this issue. Perhaps, they forgot to mark this method as obsolete. Will be back when I get a response.
> 
> thanks for the reply. I have a question to ask: From my rough attempts, whether it is get product Info or get product description, product-related APIs seem to be unable to obtain product information from other sellers. My approach is to first use the CreateProductByOzonID interface to import it into the seller's system, and then obtain its product information. If this interface is really deprecated, is there any way to get product information from other sellers?

I've got response from Ozon Seller. They say method is deprecated and you can import products only on website.
Answering your question, I'm not really sure you can get information about other sellers' products. I think Seller API is more about managing your own products. 
Not sure you can like read all the products on Ozon using their API. As I see, you want to read other people products and do something with that information. At least for now it seems to be impossible. You can ask these people for API Key with appropriate permissions to read their products.
Hope I helped you in some way. If you have more questions, please let me know.

**Comment by JoeyFrancisTribbiani** [comment]
> > > Hi! Thank you for reporting a problem. I've checked this method in Ozon Seller API documentation, it doesn't say that it's obsolete. I also tried to send a request via Postman and I got the same error. Same thing happens if I try this method via console directly in Ozon Seller API documentation. I am not sure it relates to this library, but I asked Ozon about this issue. Perhaps, they forgot to mark this method as obsolete. Will be back when I get a response.
> > 
> > 
> > thanks for the reply. I have a question to ask: From my rough attempts, whether it is get product Info or get product description, product-related APIs seem to be unable to obtain product information from other sellers. My approach is to first use the CreateProductByOzonID interface to import it into the seller's system, and then obtain its product information. If this interface is really deprecated, is there any way to get product information from other sellers?
> 
> I've got response from Ozon Seller. They say method is deprecated and you can import products only on website. Answering your question, I'm not really sure you can get information about other sellers' products. I think Seller API is more about managing your own products. Not sure you can like read all the products on Ozon using their API. As I see, you want to read other people products and do something with that information. At least for now it seems to be impossible. You can ask these people for API Key with appropriate permissions to read their products. Hope I helped you in some way. If you have more questions, please let me know.

Thank you for your help. May I ask through which channel you contacted the ozon official team? Is it through a technology partner?

**Comment by diPhantxm** [comment]
As Ozon Seller you can contact Ozon Seller Support on website https://seller.ozon.ru/
So to contact them you must be an Ozon Seller. If you are using this library, I think you already are.
I'm not sure if there is any other way to contact them

**Comment by JoeyFrancisTribbiani** [comment]
I appreciate,RESPECT
