### ISSUE TITLE
client.Warehouses().GetListOfWarehouses(context.Background()) 报错：

### ISSUE THREAD

**Issue by JoeyFrancisTribbiani** [diPhantxm/ozon-api-client#80]
<img width="809" alt="image" src="https://github.com/diPhantxm/ozon-api-client/assets/26857248/efd0b5a2-fe8e-43dc-9e4e-58d0e557d72e">

**Comment by JoeyFrancisTribbiani** [comment]
**
<img width="1919" alt="image" src="https://github.com/diPhantxm/ozon-api-client/assets/26857248/fe519ed3-9a7d-4ef4-85ff-6caae9693231">
**

**Comment by diPhantxm** [comment]
Hi! Thank you for reporting the problem.
I will look at it and return with some feedback as soon as possible.

**Comment by diPhantxm** [comment]
@JoeyFrancisTribbiani Hi again. I've fixed the issue. I will release a new version after merging #79. If you need this fix ASAP, please just let me know!

**Comment by JoeyFrancisTribbiani** [comment]
i will wait you

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
