### ISSUE TITLE
	listResp, err := client.Warehouses().GetListOfWarehouses(context.Background()) error:

### ISSUE THREAD

**Issue by JoeyFrancisTribbiani** [diPhantxm/ozon-api-client#82]
error when getting warehouse list	{"error": "json: cannot unmarshal number into Go struct field GetListOfWarehousesResult.result.working_days of type ozon.WorkingDay"}

**Comment by diPhantxm** [comment]
Hi. Thank you once again for reporting problems in this library. I'm on my way to fix it.
Want to add that this may happen due to incorrectness in official Ozon API Seller documentation. It says this field is an array of strings, but it's array of integers actually.
Will fix soon.

**Comment by diPhantxm** [comment]
Fixed in #83

**Comment by JoeyFrancisTribbiani** [comment]
waiting for new release
________________________________
发件人: Kirill ***@***.***>
发送时间: 2024年4月21日 15:42
收件人: diPhantxm/ozon-api-client ***@***.***>
抄送: elder frog ***@***.***>; Author ***@***.***>
主题: Re: [diPhantxm/ozon-api-client] listResp, err := client.Warehouses().GetListOfWarehouses(context.Background()) error: (Issue #82)


Fixed in #83<https://github.com/diPhantxm/ozon-api-client/pull/83>

―
