### ISSUE TITLE
GetStocksInfoParams.GetStocksInfoFilter - proto: syntax error (line 3:16): unexpected token %s

### ISSUE THREAD

**Issue by Fekoz** [diPhantxm/ozon-api-client#84]
/v3/product/info/stocks
GetStocksInfoParams.GetStocksInfoFilter - return error ozon proto: syntax error (line 3:16): unexpected token because of the string, not the array

current:
OfferId string
ProductId int64 

change to:
OfferId []string
ProductId []int64

**Comment by diPhantxm** [comment]
Hi! Thank you for reporting the problem and making this library better. I'll fix it as soon as possible. Or you can send PR if you wish to contribute :)
